Added pre-scan check to fail scan early and avoid pulling resources

diff --git a/scanners/boostsecurityio/bundler-audit/module.yaml b/scanners/boostsecurityio/bundler-audit/module.yaml
--- a/scanners/boostsecurityio/bundler-audit/module.yaml
+++ b/scanners/boostsecurityio/bundler-audit/module.yaml
@@ -15,6 +15,14 @@ config:
     - ${GEMFILE_LOCK:-Gemfile.lock}
 
 steps:
+  - run: |
+      GEMFILE_LOCK=${GEMFILE_LOCK:-Gemfile.lock}
+      if [ "$(ls | grep "$GEMFILE_LOCK" | wc -l)" != "0" ]
+      then
+        exit 0
+      fi
+      >&2 echo "Scan misconfiguration: Bundler audit require a $GEMFILE_LOCK file which is missing."
+      exit 1 
   - scan:
       command:
         docker:
diff --git a/scanners/boostsecurityio/npm-audit/module.yaml b/scanners/boostsecurityio/npm-audit/module.yaml
--- a/scanners/boostsecurityio/npm-audit/module.yaml
+++ b/scanners/boostsecurityio/npm-audit/module.yaml
@@ -13,6 +13,13 @@ config:
     - package-lock.json
 
 steps:
+  - run: |
+      if [ "$(ls | grep "package-lock.json" | wc -l)" != "0" ]
+      then
+        exit 0
+      fi
+      >&2 echo "Scan misconfiguration: NPM audit require a package-lock.json file which is missing."
+      exit 1 
   - scan:
       command:
         docker:
