Make validation POSIX compliant

diff --git a/scanners/boostsecurityio/semgrep/module.yaml b/scanners/boostsecurityio/semgrep/module.yaml
--- a/scanners/boostsecurityio/semgrep/module.yaml
+++ b/scanners/boostsecurityio/semgrep/module.yaml
@@ -12,16 +12,21 @@ config:
   - .semgrep/*
 
 setup:
-  - name: Config
+  - name: Validate rules
     environment:
       SEMGREP_RULES: ${SEMGREP_RULES:-https://assets.build.boostsecurity.io/semgrep-rules/stable/all-sast-rules.yml}
     run: |
       echo "SEMGREP_RULES set to: '$SEMGREP_RULES'"
       for rule in $SEMGREP_RULES; do
-        if [[ "$rule" != .semgrep/* && "$rule" != http://* && "$rule" != https://* ]]; then
-          echo "Semgrep Community Rules cannot be used. Provide a URL or relative path to rules file or leave blank for Boost curated rules."
-          exit 1
-        fi
+        case "$rule" in
+          .semgrep/*|http://*|https://*)
+            # valid rule token; do nothing
+            ;;
+          *)
+            echo "Semgrep Community Rules cannot be used. Provide a URL or relative path to rules file or leave blank for Boost curated rules."
+            exit 1
+            ;;
+        esac
       done
 
 steps:
